name: Test-Build

on:
  push:
    paths-ignore:
      - pom.xml
    branches: [master]


jobs:
  Test:
    name: Test - Units
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Testdb01.
          POSTGRES_DB: Library
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Build
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run unit tests
        run: mvn -B test --file pom.xml


